#!/usr/bin/env bash

set -euxo pipefail

dir="$1"

cd "$dir"

rbenv exec gem install bundler

rbenv exec bundle install

rbenv exec bundle exec jekyll serve --drafts --livereload --port 1337 --open-url
